sudo: required

addons:
  apt:
    packages:
      - docker-ce

language: c

services:
  - docker

install:
  - docker build -t bjcamp95/eiskaltdcpp-mutli-webui:latest .
  - docker build -t bjcamp95/eiskaltdcpp-mutli-webui:server -f Dockerfile.server .
